Inspired from Kutz, J. N., Brunton, S. L., Brunton, B. W., & Proctor, J. L. (2016). Dynamic Mode Decomposition. In Dynamic Mode Decomposition. https://doi.org/10.1137/1.9781611974508

In [28]:
using MAT, LinearAlgebra, Images

In [3]:
cd("D:\\Users\\Administrator\\Desktop\\AD\\Research\\DDSE\\CODE\\CH02_FLUIDS");

In [4]:
pwd()

"D:\\Users\\Administrator\\Desktop\\AD\\Research\\DDSE\\CODE\\CH02_FLUIDS"

In [11]:
readdir()

8-element Array{String,1}:
 ".DS_Store"
 "CCcool.mat"
 "README.txt"
 "computeDMD.m"
 "computePOD.m"
 "loadDATA.m"
 "loadIBPM.m"
 "plotCylinder.m"

In [5]:
matdata = matread("..\\DATA\\FLUIDS\\CYLINDER_ALL.mat")

Dict{String,Any} with 10 entries:
  "n"         => 449.0
  "nx"        => 199.0
  "m"         => 199.0
  "UEXTRA"    => [1.01268; 1.01211; … ; 0.899783; 0.90235]
  "ny"        => 449.0
  "VEXTRA"    => [-0.115357; -0.116494; … ; 0.156785; 0.153308]
  "VORTALL"   => [-9.37978e-15 -8.81369e-15 … -9.41491e-15 -9.30876e-15; -9.306…
  "UALL"      => [1.01243 1.01092 … 1.01606 1.01434; 1.01186 1.01034 … 1.01553 …
  "VALL"      => [-0.11537 -0.115353 … -0.114821 -0.115171; -0.116503 -0.116465…
  "VORTEXTRA" => [-8.3202e-15; -8.40734e-15; … ; -0.0316823; -0.0451625]

In [6]:
Y=matdata["VORTALL"];X=Y[:,1:end-1];X2=Y[:,2:end];

In [7]:
SVD = svd(X)

LinearAlgebra.SVD{Float64,Float64,Array{Float64,2}}
U factor:
89351×150 Array{Float64,2}:
  2.18196e-17   8.12043e-17  -4.81996e-17  …   2.64034e-10  -4.68175e-10
 -5.76805e-17   1.09447e-16  -1.16752e-17     -2.17425e-10   4.52696e-11
 -6.13578e-17   1.01897e-17   4.09067e-17      6.20211e-11  -1.85369e-10
 -4.47067e-18  -4.51624e-17  -1.17255e-16      3.66157e-11  -1.08388e-10
  2.52387e-17  -3.22637e-17  -1.156e-17       -9.72413e-11   2.96808e-10
 -4.91218e-17  -2.9481e-17    1.89328e-17  …   3.23715e-10  -9.8995e-11
 -2.68887e-17  -2.91507e-17  -3.07101e-17     -9.17145e-11   1.10564e-10
  9.47266e-18   9.36431e-18  -1.2292e-16      -5.62495e-11   1.85395e-10
  1.42284e-17   8.88897e-17  -8.87851e-17      2.41081e-11  -3.10408e-11
 -1.58685e-17   3.28328e-17  -1.03857e-16     -7.68786e-12  -4.82678e-11
 -2.73172e-17  -1.78768e-17  -6.36524e-17  …   1.59949e-11   1.73619e-10
 -1.92489e-18   8.24966e-17  -5.09544e-17      1.60829e-10  -9.17199e-11
 -3.17009e-17   9.81525e-18  -5.685

In [12]:
#  Compute DMD (Phi are eigenvectors)
r = 21  # truncate at 21 modes
U = SVD.U[:,1:r]

89351×21 Array{Float64,2}:
  2.18196e-17   8.12043e-17  -4.81996e-17  …  -9.59175e-14   4.35155e-14
 -5.76805e-17   1.09447e-16  -1.16752e-17     -1.43429e-14   1.32595e-14
 -6.13578e-17   1.01897e-17   4.09067e-17      4.07469e-15   1.10151e-14
 -4.47067e-18  -4.51624e-17  -1.17255e-16     -1.1117e-14    5.15769e-15
  2.52387e-17  -3.22637e-17  -1.156e-17       -1.16609e-15  -7.10385e-15
 -4.91218e-17  -2.9481e-17    1.89328e-17  …  -2.83851e-14  -7.22434e-15
 -2.68887e-17  -2.91507e-17  -3.07101e-17     -1.36888e-16  -3.78571e-14
  9.47266e-18   9.36431e-18  -1.2292e-16       8.66708e-15  -6.21037e-15
  1.42284e-17   8.88897e-17  -8.87851e-17      2.34486e-14   7.42018e-16
 -1.58685e-17   3.28328e-17  -1.03857e-16     -4.28757e-15  -2.44237e-14
 -2.73172e-17  -1.78768e-17  -6.36524e-17  …  -6.03548e-15   1.07332e-15
 -1.92489e-18   8.24966e-17  -5.09544e-17      4.86885e-15   3.17759e-15
 -3.17009e-17   9.81525e-18  -5.68521e-17     -3.67949e-15  -1.0804e-14
  ⋮                      

In [9]:
S = diagm(SVD.S[1:r])

21×21 Array{Float64,2}:
 3563.93     0.0      0.0     0.0    …  0.0      0.0      0.0      0.0
    0.0   1299.03     0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0   1270.28    0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0   466.096     0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0    …  0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0    …  0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0      0.0      0.0
    0.0      0.0      0.0     0.0       0.0      0.0 

In [11]:
Vt = SVD.Vt[1:r,:]

21×150 Array{Float64,2}:
  0.0817218    0.0818297   0.0818917   …   0.0812814   0.0814135
 -0.0451971   -0.0670243  -0.0863194       0.0274308   0.00488999
  0.107366     0.0956998   0.0796626       0.112711    0.116218
  0.008966     0.055033    0.0912369      -0.109708   -0.0850059
 -0.117129    -0.104786   -0.0740965      -0.0396982  -0.0793708
  0.115256     0.113247    0.0683129   …  -0.0677451  -0.00218471
  0.0389355   -0.0337157  -0.0923139       0.0937717   0.12037
 -0.0382956   -0.102336   -0.0989063       0.0933621   0.114969
 -0.109247    -0.0429758   0.0503651       0.06536    -0.0250297
  0.114178     0.0734367  -0.0369331      -0.111941   -0.0840567
 -0.026405     0.0810395   0.104681    …   0.0309354  -0.0859379
  0.116209     0.0579501  -0.0773425      -0.0659211  -0.113112
 -0.0305215    0.0983492   0.0885788       0.0931529  -0.0407889
  0.117036     0.0167675  -0.114028       -0.0111653  -0.114816
 -0.0115926    0.116251    0.0343697       0.112152   -0.00761831
  0

In [13]:
à = U'*X2*Vt'*inv(S)

21×21 Array{Float64,2}:
  0.999986     -0.000897748  -0.000133548  …   0.00111725    0.000230894
  0.000910772   0.977843     -0.209509        -8.17778e-6    0.000192505
  0.000254427   0.203275      0.979009         6.71172e-5   -1.47374e-5
 -0.000499744  -3.43021e-5   -0.00267733      -0.00116229   -0.00285656
  0.000272426  -0.00131712    0.000402129      0.00918791    0.00448244
 -0.000418776   0.00278602   -0.00168255   …  -0.000128418  -7.60964e-5
  0.000530142  -0.00232436    0.00208709      -0.000168757  -0.000429142
  0.000341933  -6.17367e-5    0.00137902       0.000833096  -0.00358545
  2.61402e-5   -0.000323676   9.11222e-5      -0.00845384   -0.00788661
 -0.000154603   9.34358e-5   -0.000609233      0.000100638  -0.000945113
 -0.000165279  -0.000122627  -0.000673255  …  -0.00046013    0.000502896
 -0.000103975   7.29476e-5   -0.000409813      0.00981972   -0.00231024
 -8.2922e-5    -3.71028e-5   -0.000334741     -0.00241368    0.00891914
 -6.59358e-5    4.12177e-5   -0.000

In [14]:
F = eigen(Ã)
Phi = X2*Vt'*inv(S)*F.vectors

89351×21 Array{Complex{Float64},2}:
  2.91646e-17+8.85125e-17im   2.91646e-17-8.85125e-17im  …   1.7365e-17+0.0im
 -4.20173e-18+1.13e-16im     -4.20173e-18-1.13e-16im        1.75079e-17+0.0im
   7.7204e-18+1.06692e-16im    7.7204e-18-1.06692e-16im       1.763e-17+0.0im
  2.59786e-17+8.8411e-17im    2.59786e-17-8.8411e-17im      1.76656e-17+0.0im
    1.688e-17+1.04467e-16im     1.688e-17-1.04467e-16im     1.77846e-17+0.0im
 -1.18982e-17+1.14877e-16im  -1.18982e-17-1.14877e-16im  …  1.79706e-17+0.0im
 -7.53051e-18+1.50394e-16im  -7.53051e-18-1.50394e-16im     1.82263e-17+0.0im
 -2.15988e-17+1.7423e-16im   -2.15988e-17-1.7423e-16im      1.83694e-17+0.0im
  3.90372e-18+1.49406e-16im   3.90372e-18-1.49406e-16im     1.86352e-17+0.0im
 -4.01809e-18+1.53573e-16im  -4.01809e-18-1.53573e-16im     1.90566e-17+0.0im
 -1.04027e-17+1.34434e-16im  -1.04027e-17-1.34434e-16im  …  1.93611e-17+0.0im
    6.163e-18+1.23193e-16im     6.163e-18-1.23193e-16im     1.94664e-17+0.0im
  1.68357e-17+7.84701e-17im 

In [24]:
MeanFlow=reshape(real(Phi[:,9]),Int64(matdata["nx"]),Int64(matdata["ny"]))

199×449 Array{Float64,2}:
 -1.02387e-18  -2.11773e-18  -3.50661e-18  …   0.000787535   0.000655213
 -1.66629e-18  -1.37682e-18  -1.47255e-18      0.000993099   0.000860693
 -1.12517e-18  -1.43638e-19   2.2421e-19       0.00120168    0.00107188
  1.1339e-18   -5.79523e-19  -8.20011e-19      0.00140734    0.00128345
  3.71339e-18   1.24098e-18   1.26672e-18      0.00160368    0.0014907
  4.1549e-18   -6.96553e-19  -3.15283e-18  …   0.00178479    0.00168602
 -8.31073e-19  -2.13224e-18  -3.04267e-18      0.00194467    0.00186595
 -3.41356e-18  -2.13944e-18  -1.92226e-18      0.00207833    0.00202242
 -6.66694e-18  -3.42724e-18  -5.81337e-18      0.00218122    0.00215414
 -8.47206e-18  -7.21508e-18  -9.25962e-18      0.00225026    0.00225385
 -1.2046e-17   -1.07328e-17  -1.45028e-17  …   0.00228316    0.00232291
 -1.80273e-17  -1.54247e-17  -2.29624e-17      0.00227927    0.00235584
 -1.94586e-17  -1.75552e-17  -2.5992e-17       0.00223889    0.00235656
  ⋮                                  

In [31]:
imshow(MeanFlow)

Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}("window"=>GtkWindowLeaf(name="", parent, wi…
  "roi"         => Dict{String,Any}("redraw"=>74: "map(clim-mapped image, input…
  "annotations" => 40: "input-14" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 39: "CLim" = CLim{Float64}(-0.0147285, 0.014748) CLim{Float6…