# Radial Basis Function

In [28]:
X=[1 2 3 1 2 3 1 2 3;1 1 1 2 2 2 3 3 3]

2×9 Array{Int64,2}:
 1  2  3  1  2  3  1  2  3
 1  1  1  2  2  2  3  3  3

In [29]:
 Xint=[1.5 1.1 2.5;1.5 1.2 2.5]

2×3 Array{Float64,2}:
 1.5  1.1  2.5
 1.5  1.2  2.5

In [32]:
f(x)=[sqrt(x[1]), x[2]^2, x[1]+x[2]]

f (generic function with 1 method)

In [33]:
Y=zeros(3,9)
for i in 1:9
    Y[:,i]=f(X[:,i])
end
Y

3×9 Array{Float64,2}:
 1.0  1.41421  1.73205  1.0  1.41421  1.73205  1.0  1.41421  1.73205
 1.0  1.0      1.0      4.0  4.0      4.0      9.0  9.0      9.0
 2.0  3.0      4.0      3.0  4.0      5.0      4.0  5.0      6.0

## Choice of two types of Radial Basis Function :
* Linear spline (G1)
* Cubic spline (G2)

In [34]:
G1=zeros(9,9)
for i in 1:9
    for j in 1:9
    G1[i,j]=sqrt((X[:,i][1]-X[:,j][1])^2+(X[:,i][2]-X[:,j][2])^2)
    end
end
G1

9×9 Array{Float64,2}:
 0.0      1.0      2.0      1.0      …  2.23607  2.0      2.23607  2.82843
 1.0      0.0      1.0      1.41421     1.41421  2.23607  2.0      2.23607
 2.0      1.0      0.0      2.23607     1.0      2.82843  2.23607  2.0
 1.0      1.41421  2.23607  0.0         2.0      1.0      1.41421  2.23607
 1.41421  1.0      1.41421  1.0         1.0      1.41421  1.0      1.41421
 2.23607  1.41421  1.0      2.0      …  0.0      2.23607  1.41421  1.0
 2.0      2.23607  2.82843  1.0         2.23607  0.0      1.0      2.0
 2.23607  2.0      2.23607  1.41421     1.41421  1.0      0.0      1.0
 2.82843  2.23607  2.0      2.23607     1.0      2.0      1.0      0.0

In [35]:
G2=zeros(9,9)
for i in 1:9
    for j in 1:9
    G2[i,j]=sqrt((X[:,i][1]-X[:,j][1])^2+(X[:,i][2]-X[:,j][2])^2)^3
    end
end
G2

9×9 Array{Float64,2}:
  0.0       1.0       8.0       1.0      …   8.0      11.1803   22.6274
  1.0       0.0       1.0       2.82843     11.1803    8.0      11.1803
  8.0       1.0       0.0      11.1803      22.6274   11.1803    8.0
  1.0       2.82843  11.1803    0.0          1.0       2.82843  11.1803
  2.82843   1.0       2.82843   1.0          2.82843   1.0       2.82843
 11.1803    2.82843   1.0       8.0      …  11.1803    2.82843   1.0
  8.0      11.1803   22.6274    1.0          0.0       1.0       8.0
 11.1803    8.0      11.1803    2.82843      1.0       0.0       1.0
 22.6274   11.1803    8.0      11.1803       8.0       1.0       0.0

In [36]:
A1=Y*(inv(G1'))'

3×9 Array{Float64,2}:
 0.367804  -0.0436572  0.152806  …   0.367804  -0.0436572   0.152806
 1.72823    0.161643   1.72823      -0.621314  -0.934163   -0.621314
 1.30171    0.126765   0.714327      0.714327  -0.147186    0.126941

In [37]:
A2=Y*(inv(G2'))'

3×9 Array{Float64,2}:
 0.27631   -0.331726  0.215527  -0.383887  …  0.27631   -0.331726  0.215527
 0.980982  -0.967142  0.980982  -1.04863      0.316732  -0.276571  0.316732
 0.856022  -1.03782   0.68996   -1.03782      0.68996   -0.865181  0.523898

Calculate the RBF interpolated value of the fonction for Xint

In [42]:
g=zeros(9,3)

9×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [45]:
for j in 1:3
    for i=1:9
    g[i,j]=sqrt((Xint[:,j][1]-X[:,j][1])^2+(Xint[:,j][2]-X[:,j][2])^2)
end
end
g

9×3 Array{Float64,2}:
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114

In [48]:
g1=zeros(9)
for i in 1:9
g1[i]=sqrt((1.5-X[:,i][1])^2+(1.5-X[:,i][2])^2)
end
g1

9-element Array{Float64,1}:
 0.7071067811865476
 0.7071067811865476
 1.5811388300841898
 0.7071067811865476
 0.7071067811865476
 1.5811388300841898
 1.5811388300841898
 1.5811388300841898
 2.1213203435596424

In [49]:
g2=zeros(9)
for i in 1:9
g2[i]=sqrt((1.1-X[:,i][1])^2+(1.2-X[:,i][2])^2)
end
g2

9-element Array{Float64,1}:
 0.22360679774997896
 0.9219544457292886
 1.91049731745428
 0.806225774829855
 1.2041594578792296
 2.0615528128088303
 1.8027756377319948
 2.0124611797498106
 2.6172504656604803

In [51]:
g3=zeros(9)
for i in 1:9
g3[i]=sqrt((2.5-X[:,i][1])^2+(2.5-X[:,i][2])^2)
end
g3

9-element Array{Float64,1}:
 2.1213203435596424
 1.5811388300841898
 1.5811388300841898
 1.5811388300841898
 0.7071067811865476
 0.7071067811865476
 1.5811388300841898
 0.7071067811865476
 0.7071067811865476

In [52]:
f1=A1*g1

3-element Array{Float64,1}:
 1.138303850496928
 2.0769803445205515
 2.756639112959866

In [55]:
f2=A1*g2

3-element Array{Float64,1}:
 1.0177206443731015
 1.4070346853046365
 2.204142798417518

In [56]:
f3=A1*g3

3-element Array{Float64,1}:
 1.5299989984668725
 6.357504525848947
 4.896901203624063