# Radial Basis Function

In [1]:
X=[1 2 3 1 2 3 1 2 3;1 1 1 2 2 2 3 3 3]

2×9 Array{Int64,2}:
 1  2  3  1  2  3  1  2  3
 1  1  1  2  2  2  3  3  3

In [2]:
 Xint=[1.5 1.1 2.5;1.5 1.2 2.5]

2×3 Array{Float64,2}:
 1.5  1.1  2.5
 1.5  1.2  2.5

In [3]:
f(x)=[sqrt(x[1]), x[2]^2, x[1]+x[2]]

f (generic function with 1 method)

In [4]:
Y=zeros(3,9)
for i in 1:9
    Y[:,i]=f(X[:,i])
end
Y

3×9 Array{Float64,2}:
 1.0  1.41421  1.73205  1.0  1.41421  1.73205  1.0  1.41421  1.73205
 1.0  1.0      1.0      4.0  4.0      4.0      9.0  9.0      9.0
 2.0  3.0      4.0      3.0  4.0      5.0      4.0  5.0      6.0

## Choice of two types of Radial Basis Function :
* Linear spline (G1)
* Cubic spline (G2)

RBF : Linear Spline

In [5]:
G1=zeros(9,9)
for i in 1:9
    for j in 1:9
    G1[i,j]=sqrt((X[:,i][1]-X[:,j][1])^2+(X[:,i][2]-X[:,j][2])^2)
    end
end
G1

9×9 Array{Float64,2}:
 0.0      1.0      2.0      1.0      …  2.23607  2.0      2.23607  2.82843
 1.0      0.0      1.0      1.41421     1.41421  2.23607  2.0      2.23607
 2.0      1.0      0.0      2.23607     1.0      2.82843  2.23607  2.0
 1.0      1.41421  2.23607  0.0         2.0      1.0      1.41421  2.23607
 1.41421  1.0      1.41421  1.0         1.0      1.41421  1.0      1.41421
 2.23607  1.41421  1.0      2.0      …  0.0      2.23607  1.41421  1.0
 2.0      2.23607  2.82843  1.0         2.23607  0.0      1.0      2.0
 2.23607  2.0      2.23607  1.41421     1.41421  1.0      0.0      1.0
 2.82843  2.23607  2.0      2.23607     1.0      2.0      1.0      0.0

In [6]:
G2=zeros(9,9)
for i in 1:9
    for j in 1:9
    G2[i,j]=sqrt((X[:,i][1]-X[:,j][1])^2+(X[:,i][2]-X[:,j][2])^2)^3
    end
end
G2

9×9 Array{Float64,2}:
  0.0       1.0       8.0       1.0      …   8.0      11.1803   22.6274
  1.0       0.0       1.0       2.82843     11.1803    8.0      11.1803
  8.0       1.0       0.0      11.1803      22.6274   11.1803    8.0
  1.0       2.82843  11.1803    0.0          1.0       2.82843  11.1803
  2.82843   1.0       2.82843   1.0          2.82843   1.0       2.82843
 11.1803    2.82843   1.0       8.0      …  11.1803    2.82843   1.0
  8.0      11.1803   22.6274    1.0          0.0       1.0       8.0
 11.1803    8.0      11.1803    2.82843      1.0       0.0       1.0
 22.6274   11.1803    8.0      11.1803       8.0       1.0       0.0

In [7]:
A1=Y*(inv(G1'))'

3×9 Array{Float64,2}:
 0.367804  -0.0436572  0.152806  …   0.367804  -0.0436572   0.152806
 1.72823    0.161643   1.72823      -0.621314  -0.934163   -0.621314
 1.30171    0.126765   0.714327      0.714327  -0.147186    0.126941

In [8]:
A2=Y*(inv(G2'))'

3×9 Array{Float64,2}:
 0.27631   -0.331726  0.215527  -0.383887  …  0.27631   -0.331726  0.215527
 0.980982  -0.967142  0.980982  -1.04863      0.316732  -0.276571  0.316732
 0.856022  -1.03782   0.68996   -1.03782      0.68996   -0.865181  0.523898

Calculate the RBF interpolated value of the fonction for Xint

In [9]:
g=zeros(9,3)

9×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [10]:
#Wrong
for j in 1:3
    for i=1:9
    g[i,j]=sqrt((Xint[:,j][1]-X[:,j][1])^2+(Xint[:,j][2]-X[:,j][2])^2)
end
end
g

9×3 Array{Float64,2}:
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114
 0.707107  0.921954  1.58114

In [11]:
#Node 1 (1.5,1.5)
g₁¹=zeros(9)
for i in 1:9
g₁¹[i]=sqrt((1.5-X[:,i][1])^2+(1.5-X[:,i][2])^2)
end
g₁¹

9-element Array{Float64,1}:
 0.7071067811865476
 0.7071067811865476
 1.5811388300841898
 0.7071067811865476
 0.7071067811865476
 1.5811388300841898
 1.5811388300841898
 1.5811388300841898
 2.1213203435596424

In [12]:
#Node 2 (1.1,1.1)
g₁²=zeros(9)
for i in 1:9
g₁²[i]=sqrt((1.1-X[:,i][1])^2+(1.2-X[:,i][2])^2)
end
g₁²

9-element Array{Float64,1}:
 0.22360679774997896
 0.9219544457292886
 1.91049731745428
 0.806225774829855
 1.2041594578792296
 2.0615528128088303
 1.8027756377319948
 2.0124611797498106
 2.6172504656604803

In [13]:
#Node 3 (2.5,2.5)
g₁³=zeros(9)
for i in 1:9
g₁³[i]=sqrt((2.5-X[:,i][1])^2+(2.5-X[:,i][2])^2)
end
g₁³

9-element Array{Float64,1}:
 2.1213203435596424
 1.5811388300841898
 1.5811388300841898
 1.5811388300841898
 0.7071067811865476
 0.7071067811865476
 1.5811388300841898
 0.7071067811865476
 0.7071067811865476

In [14]:
f₁¹=A1*g₁¹

3-element Array{Float64,1}:
 1.1383038504969272
 2.0769803445205515
 2.756639112959866

In [15]:
f₁²=A1*g₁²

3-element Array{Float64,1}:
 1.0177206443731004
 1.4070346853046354
 2.204142798417519

In [16]:
f₁³=A1*g₁³

3-element Array{Float64,1}:
 1.5299989984668718
 6.357504525848945
 4.896901203624062

RBF : Cubic Spline

In [17]:
#Node 1 (1.5,1.5)
g₂¹=zeros(9)
for i in 1:9
g₂¹[i]=sqrt((1.5-X[:,i][1])^2+(1.5-X[:,i][2])^2)^3
end
g₂¹

9-element Array{Float64,1}:
 0.35355339059327384
 0.35355339059327384
 3.952847075210475
 0.35355339059327384
 0.35355339059327384
 3.952847075210475
 3.952847075210475
 3.952847075210475
 9.545941546018389

In [18]:
#Node 2 (1.1,1.1)
g₂²=zeros(9)
for i in 1:9
g₂²[i]=sqrt((1.1-X[:,i][1])^2+(1.2-X[:,i][2])^2)^3
end
g₂²

9-element Array{Float64,1}:
  0.011180339887498947
  0.7836612788698952
  6.973315208708123
  0.5240467536394059
  1.7460312139248833
  8.761599454437528
  5.859020822628984
  8.150467777986734
 17.928165689774293

In [20]:
#Node 3 (2.5,2.5)
g₂³=zeros(9)
for i in 1:9
g₂³[i]=sqrt((2.5-X[:,i][1])^2+(2.5-X[:,i][2])^2)^3
end
g₂³

9-element Array{Float64,1}:
 9.545941546018389
 3.952847075210475
 3.952847075210475
 3.952847075210475
 0.35355339059327384
 0.35355339059327384
 3.952847075210475
 0.35355339059327384
 0.35355339059327384

In [21]:
f₂¹=A2*g₂¹

3-element Array{Float64,1}:
 1.2921213776313563
 2.5844223787819507
 3.250638435276149

In [22]:
f₂²=A2*g₂²

3-element Array{Float64,1}:
 1.1367423567256028
 1.811487244689955
 2.5925893416474697

In [23]:
f₂³=A2*g₂³

3-element Array{Float64,1}:
 1.6234173643382157
 6.204892250889179
 5.0608733713297624